# -*- coding: utf-8 -*-
"""flower_classi_CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18quAo1CF0te1LJS5aRK27OT4rzqQQP3f
"""

import cv2
from glob import glob
import pathlib
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt


from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten,Dense,Conv3D,MaxPool3D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

veg_path=pathlib.Path(r"C:\Users\fathi\OneDrive\Desktop\CNN_PROJECTS\flower\dataset")

zero_list=list(veg_path.glob("daisy/*.jpg"))          # *-shows all #(malignant/*)- shows all files inside the malignant folder
one_list=list(veg_path.glob("dandelion/*.jpg"))
two_list=list(veg_path.glob("rose/*.jpg"))
three_list=list(veg_path.glob("sunflower/*.jpg"))
four_list=list(veg_path.glob("tulip/*.jpg"))

len(zero_list),len(one_list),len(two_list),len(three_list),len(four_list)

veg_dict={"daisy":zero_list,
              "dandelion":one_list,
              "rose":two_list,
              "sunflower":three_list,
              "tulip":four_list,
             }
veg_class={"daisy":0,
              "dandelion":1,
               "rose":2,
               "sunflower":3,
               "tulip":4,

              }

x=[]
y=[]

for i in veg_dict:
  veg_name=i
  veg_path_list=veg_dict[veg_name]
  for path in veg_path_list:
    img=cv2.imread(str(path))
    img=cv2.resize(img,(224,224))
    img=img/255
    x.append(img)
    cls=veg_class[veg_name]
    y.append(cls)

len(x)

x=np.array(x)
y=np.array(y)

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.75,random_state=1)

len(xtrain),len(ytrain),len(xtest),len(ytest)

xtrain.shape

xtrain.shape,xtest.shape

#from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2

#base_model = tf.keras.applications.MobileNetV2(input_shape=(32, 32, 3),include_top=False,weights='imagenet')

#print("[INFO] summary for base model...")
#print(base_model.summary())

from tensorflow.keras.layers import MaxPooling2D
from keras.layers.core import Dropout
from tensorflow.keras import datasets, layers, models
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(5,activation='softmax'))

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(xtrain, ytrain, epochs=10,
                    validation_data=(xtest, ytest))

#model_hist=model.fit(xtrain,ytrain,epochs=5,validation_data=(xtest,ytest),batch_size=180)

model.save("weight.h5")

